# Generated by Django 5.0.3 on 2024-03-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='time_period',
        ),
    ]
