# Generated by Django 5.0.3 on 2024-03-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='option_state',
            name='option_m',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='name',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='answers',
            name='is_True',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='answers',
            name='type',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.test')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.question'),
        ),
        migrations.DeleteModel(
            name='correct_answer',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='option_state',
        ),
    ]
