# Generated by Django 4.2.7 on 2024-03-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ques',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
