# Generated by Django 5.0.3 on 2024-03-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='correct_answer',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='exercise',
            name='optionOne',
            field=models.BooleanField(default=False),
        ),
    ]
