# Generated by Django 5.0.3 on 2024-03-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_exercise_question_remove_answers_ans_and_more'),
        ('school', '0002_remove_grade_time_period'),
    ]

    operations = [
    ]
