# Generated by Django 4.2.7 on 2024-03-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_test_ques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='ques',
        ),
    ]
