# Generated by Django 5.0.3 on 2024-03-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_exercise_correct_answer_exercise_optionone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='optionOne',
        ),
        migrations.CreateModel(
            name='correct_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('correct_ans', models.ManyToManyField(related_name='correct_ans', to='school.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='option_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_s', models.BooleanField(default=False)),
                ('option_m', models.ManyToManyField(related_name='option_m', to='school.exercise')),
            ],
        ),
    ]
