# Generated by Django 5.0.3 on 2024-03-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_merge_20240315_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='holder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
    ]
