# Generated by Django 5.0.3 on 2024-03-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_exams_grade_homework_school_class_student_and_more'),
        ('school', '0003_remove_test_ques'),
    ]

    operations = [
    ]
