# Generated by Django 5.0.3 on 2024-03-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_grade_grade_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(default='User Alt Tabbed', max_length=100),
        ),
    ]
