# Generated by Django 5.0.3 on 2024-03-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_grade_type_alter_grade_grade'),
        ('school', '0006_alter_log_message'),
    ]

    operations = [
    ]
