# Generated by Django 5.0.3 on 2024-03-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_merge_20240316_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grades',
        ),
    ]
