# Generated by Django 5.0.3 on 2024-03-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_student_grades'),
        ('school', '0008_remove_student_grades'),
    ]

    operations = [
    ]
